### ISSUE TITLE
get_attachment_ids returns invalid IDs due to filename and parsing bug

### ISSUE THREAD

**Issue by djstauffer** [RT-Client-REST/RT-Client-REST#11]
The last statement in the get_attachment_ids sub (in REST.pm) contains this code:

`return $k->{Attachments} =~ m/(\d+):/mg;`

The text that regex is matching against will look something like this:

<pre>
179256: (Unnamed) (text/plain / 785b),
179257: (Unnamed) (multipart/mixed / 0b),
179258: (Unnamed) (text/plain / 33b),
179259: somefile.pdf (application/pdf / 17.2k),
179260: strangefilename 02:01:34.pdf (application/pdf / 338.3k),
</pre>

The problem is, in the case of "strangefilename 02:01:18.pdf", the regex above will match "02" and "01" in the filename and think they are attachment IDs.

I found this problem because of just such a filename being used as an attachment.

Here is a diff that can be applied to the REST.pm file to fix the problem:

<pre>
155c155
<     return $k->{Attachments} =~ m/(\d+):/mg;
---
>     return $k->{Attachments} =~ m/^\s*(\d+):/mg;
</pre>

**Comment by dtikhonov** [comment]
I applied your fix in 0.51:

https://metacpan.org/release/DMITRI/RT-Client-REST-0.51

Thanks!

**Comment by djstauffer** [comment]
cool, glad to be of some help.
