### ISSUE TITLE
RT-Client-REST2 Repo

### ISSUE THREAD

**Issue by djzort** [RT-Client-REST/RT-Client-REST#15]
RT's "REST2" interface is actually RESTful and is completely different, I think this justifies a new implementation rather than trying to smoosh everything in to one library.

If people are comfortable with this assessment, could someone please create a new repo in this project called RT-Client-REST2 (or... perhaps naming is something to discuss)

**Comment by dtikhonov** [comment]
Do they provide a command-line tool?  I used that as a starting point (basis for REST.pm) when I made the library.

**Comment by djzort** [comment]
See also 

- https://bestpractical.com/blog/2017/7/rest2-public-beta-and-request-for-comment 
- https://github.com/bestpractical/rt-extension-rest2

**Comment by dtikhonov** [comment]
I looked at their repo -- it does not look like there is a command-line tool for talking to REST2.  Of course, now that the serialization format is more standard and the POSTs, GETs, and so on are documented, there is less of a reason to have a dedicated library.  On the other hand, such library is now easier to write.
