### ISSUE TITLE
Allow HTML in comments

### ISSUE THREAD

**Issue by mttpg** [RT-Client-REST/RT-Client-REST#20]
It would be very useful to be able to post HTML comments as well as plain text comments, especially for URLs. According to the RT REST API, it is possible to specify `Content-Type: text/html` for comments.

**Comment by djzort** [comment]
hi @mttpg can you provide an example of what this might look like if added to the API ?

**Comment by djzort** [comment]
See 915b519fc73ede2db1a9453b6bdbacd14c9cbbe9
