### ISSUE TITLE
'uninitialized value' message when calling get_attachments_metadata()

### ISSUE THREAD

**Issue by djstauffer** [RT-Client-REST/RT-Client-REST#22]
when calling get_attachments_metadata() I am getting the message:

 "Use of uninitialized value $c[1] in string eq at /usr/share/perl5/RT/Client/REST.pm line 177." 

I have a fix, and will submit a pull request.

**Comment by djstauffer** [comment]
Pull request #24 is targeted at this issue.

**Comment by djzort** [comment]
merged pr

**Comment by djzort** [comment]
releasing to cpan in 0.60
