### ISSUE TITLE
tests hang CPAN client with http proxy configured

### ISSUE THREAD

**Issue by glasswalk3r** [RT-Client-REST/RT-Client-REST#9]
I have a OpenBSD smoker that hangs every time it tries to test RT-Client-REST.

Narrowing it down, it seems a problem with the CPAN client `http_proxy`: I configured it to 127.0.0.1:8080 so I could disable CPAN client trying to reach out my network (instead of using my local CPAN mirror).

[Here](https://www.dropbox.com/sh/a9f7ccqi2x6gj61/AADyVAeHMmhK-19rajE_Y9VFa?dl=0&preview=2017-04-10+18_52_49-Program+Manager.png) is a screenshot with the error messages.

Anyway, once the `http_proxy` is set to a empty string, it all works fine. You should receive a report from me (ARFREITAS) using the following perl configuration:

```
Summary of my perl5 (revision 5 version 24 subversion 1) configuration:

  Platform:
    osname=openbsd, osvers=6.0, archname=OpenBSD.amd64-openbsd
    uname='openbsd salompas.spo.virtua.com.br 6.0 generic.mp#2319 amd64 '
    config_args='-de -Dprefix=/home/bar/perl5/perlbrew/perls/perl-5.24.1 -Aeval:scriptdir=/home/bar/perl5/perlbrew/perls/perl-5.24.1/bin'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
```

This issue can be reproduced by simply configuring http_proxy on CPAN client again. If it is tested by issuing:

```
perl Makefile.PL
make
make test
```

All tests pass.

By now I'll have to disable the distribution on my smoker by setting a distribution preferences file for that. Unfortunately the CPAN [client doesn't support](http://search.cpan.org/~andk/CPAN-2.16/lib/CPAN.pm#Language_Specs) enabling/disabling the proxy with a distro prefs file.

**Comment by dtikhonov** [comment]
If you paste a patch to fix (or at least omit) the test on OpenBSD, I'll apply it.

**Comment by glasswalk3r** [comment]
I guess we can close this issue... please consider the test below:

```
-bash-4.4$ cpan CPAN::SQLite
CPAN::SQLite not installed, trying to work without
Going to read '/home/vegeta/.cpan/Metadata'
  Database was generated on Tue, 27 Feb 2018 21:29:03 GMT
Running install for module 'CPAN::SQLite'
Running make for S/ST/STRO/CPAN-SQLite-0.211.tar.gz
Checksum for /minicpan/authors/id/S/ST/STRO/CPAN-SQLite-0.211.tar.gz ok

  CPAN.pm: Going to build S/ST/STRO/CPAN-SQLite-0.211.tar.gz

CPAN::Reporter not installed.  No reports will be sent.
Checking if your kit is complete...
Looks good
Warning: prerequisite DBD::SQLite 1.27 not found.
Writing Makefile for CPAN::SQLite
---- Unsatisfied dependencies detected during ----
----       STRO/CPAN-SQLite-0.211.tar.gz      ----
    DBD::SQLite [build_requires]
Running make test
  Delayed until after prerequisites
Running make install
  Delayed until after prerequisites
Running install for module 'DBD::SQLite'
Running make for I/IS/ISHIGAKI/DBD-SQLite-1.54.tar.gz
Could not find '/minicpan/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.54.tar.gz'
  LWP not available
Warning: no success downloading '/home/vegeta/.cpan/sources/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.54.tar.gz.tmp45975'. Giving up on it. at /home/vegeta/perl5/perlbrew/perls/perl-5.10.1/lib/5.10.1/CPAN/Distribution.pm line 379
Could not find '/minicpan/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.54.tar.gz'
  LWP not available
Warning: no success downloading '/home/vegeta/.cpan/sources/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.54.tar.gz.tmp45975'. Giving up on it. at /home/vegeta/perl5/perlbrew/perls/perl-5.10.1/lib/5.10.1/CPAN/Distribution.pm line 379


You have not configured a urllist and do not allow connections to the
internet to get a list of mirrors.  If you wish to get a list of CPAN
mirrors to pick from, use this command

    o conf init connect_to_internet_ok urllist

If you do not wish to get a list of mirrors and would prefer to set
your urllist manually, use just this command instead

    o conf init urllist
```

If I was needing to disable `http_proxy`  due avoiding the cpan client to go to the internet, now it doesn't seem to be the case anymore.

Anyway, I think it would be hard to find out if RT-Client-REST should rely or not on environment variables... unless you consider designing it to use a command line option instead.

If you think it is desirable, I would be happy to send you a patch... otherwise I think it is safe to close this one.

**Comment by djzort** [comment]
Might I suggest https://metacpan.org/pod/Test::RequiresInternet
